# file generated by setuptools-scm
# don't change, don't track in version control
from __future__ import annotations

__all__ = ["__version__", "__version_tuple__", "version", "version_tuple"]

TYPE_CHECKING = False
if TYPE_CHECKING:

    VERSION_TUPLE = tuple[int | str, ...]
else:
    VERSION_TUPLE = object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE

__version__ = version = "1.0.2.dev9+g004d3ef.d20250627"
__version_tuple__ = version_tuple = (1, 0, 2, "dev9", "g004d3ef.d20250627")
